// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewMotor struct {
	Text        string `json:"text"`
	User        string `json:"user"`
	Association string `json:"association"`
	Numero      string `json:"numero"`
	Parking     string `json:"parking"`
	City        string `json:"city"`
}

type NewTransaction struct {
	From      string  `json:"from"`
	To        string  `json:"to"`
	Amount    float64 `json:"amount"`
	Operation string  `json:"operation"`
}

type NewUser struct {
	Name          string  `json:"name"`
	Phone         string  `json:"phone"`
	Password      string  `json:"password"`
	DateNaissance int     `json:"dateNaissance"`
	Avatar        *string `json:"avatar"`
	Address       string  `json:"address"`
}

type UpdateMotor struct {
	Text        *string `json:"text"`
	Association *string `json:"association"`
	Numero      *string `json:"numero"`
	Parking     *string `json:"parking"`
	City        *string `json:"city"`
}

type UpdateUser struct {
	Name          *string `json:"name"`
	DateNaissance *int    `json:"dateNaissance"`
	Avatar        *string `json:"avatar"`
	Address       *string `json:"address"`
}
